#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# PhotoSync Azure Infrastructure Deployment Script
# Run this on your local machine (needs Azure CLI installed)
# ============================================================

# Configuration
RESOURCE_GROUP="${PHOTOSYNC_RG:-photosync-rg}"
LOCATION="${PHOTOSYNC_LOCATION:-eastus}"
STORAGE_NAME="${PHOTOSYNC_STORAGE:-}"
DEPLOYMENT_NAME="photosync-infra-$(date +%Y%m%d%H%M%S)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check prerequisites
log_info "Checking prerequisites..."

if ! command -v az &> /dev/null; then
    log_error "Azure CLI not found. Install: https://aka.ms/installazurecli"
    exit 1
fi

if ! az account show &> /dev/null; then
    log_error "Not logged in to Azure. Run: az login"
    exit 1
fi

CURRENT_SUB=$(az account show --query name -o tsv)
log_info "Using subscription: $CURRENT_SUB"

# Create resource group if not exists
log_info "Ensuring resource group '$RESOURCE_GROUP' exists..."
az group create \
    --name "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --output none

# Generate storage name if not provided
if [ -z "$STORAGE_NAME" ]; then
    RANDOM_SUFFIX=$(openssl rand -hex 4 | tr '[:upper:]' '[:lower:]')
    STORAGE_NAME="photosync${RANDOM_SUFFIX}"
    log_warn "Storage account name not set, generated: $STORAGE_NAME"
fi

# Validate storage name
if ! [[ "$STORAGE_NAME" =~ ^[a-z0-9]{3,24}$ ]]; then
    log_error "Storage account name must be 3-24 lowercase alphanum. Got: $STORAGE_NAME"
    exit 1
fi

# Check if storage name is globally available
log_info "Checking storage account name availability..."
AVAILABLE=$(az storage account check-name --name "$STORAGE_NAME" --query nameAvailable -o tsv)
if [ "$AVAILABLE" != "true" ]; then
    log_error "Storage account name '$STORAGE_NAME' is not available globally. Choose another."
    exit 1
fi

# Deploy Bicep
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log_info "Deploying infrastructure..."
az deployment group create \
    --resource-group "$RESOURCE_GROUP" \
    --name "$DEPLOYMENT_NAME" \
    --template-file "$SCRIPT_DIR/main.bicep" \
    --parameters \
        storageAccountName="$STORAGE_NAME" \
        defaultBlobTier="Cool" \
        archiveAfterDays=180 \
    --output none

# Get outputs
log_info "Retrieving deployment outputs..."
STORAGE_KEY=$(az storage account keys list \
    --resource-group "$RESOURCE_GROUP" \
    --account-name "$STORAGE_NAME" \
    --query '[0].value' -o tsv)

BLOB_ENDPOINT=$(az storage account show \
    --resource-group "$RESOURCE_GROUP" \
    --name "$STORAGE_NAME" \
    --query primaryEndpoints.blob -o tsv)

# Generate secrets
SECRET_KEY=$(openssl rand -hex 32)
PASSWORD="${PHOTOSYNC_PASSWORD:-family}"

# Save credentials
CREDENTIALS_FILE="${SCRIPT_DIR}/../.env.deploy"
cat > "$CREDENTIALS_FILE" <<EOF
# Auto-generated by deploy.sh on $(date)
# Copy these to your VM's .env file

AZURE_STORAGE_ACCOUNT=${STORAGE_NAME}
AZURE_STORAGE_KEY=${STORAGE_KEY}
AZURE_STORAGE_CONTAINER=photos
AZURE_STORAGE_TIER=Cool
SECRET_KEY=${SECRET_KEY}
PHOTOSYNC_PASSWORD=${PASSWORD}
EOF

chmod 600 "$CREDENTIALS_FILE"

# Summary
echo ""
echo "============================================================"
echo -e "${GREEN}Deployment Complete!${NC}"
echo "============================================================"
echo ""
echo "Resource Group:     $RESOURCE_GROUP"
echo "Location:           $LOCATION"
echo "Storage Account:    $STORAGE_NAME"
echo "Blob Endpoint:      $BLOB_ENDPOINT"
echo ""
echo -e "${YELLOW}Credentials saved to:${NC} $CREDENTIALS_FILE"
echo -e "${RED}Keep this file secure - it contains storage keys!${NC}"
echo ""
echo "Next steps:"
echo "  1. Copy $CREDENTIALS_FILE to your VM as .env"
echo "  2. Run ./scripts/setup-vm.sh on the VM"
echo ""
