#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# PhotoSync VM Setup Script
# Run this ON THE AZURE VM via SSH
# ============================================================

INSTALL_DIR="${PHOTOSYNC_DIR:-/opt/photosync}"
COMPOSE_VERSION="v2.27.0"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Must run as root for docker install
if [ "$EUID" -ne 0 ] && ! command -v docker &> /dev/null; then
    log_warn "Docker not found. To install Docker, run this script as root:"
    log_warn "  sudo ./setup-vm.sh"
    exit 1
fi

# ============================================================
# 1. Install Docker & Docker Compose (if missing)
# ============================================================
install_docker() {
    if command -v docker &> /dev/null; then
        log_info "Docker already installed: $(docker --version)"
        return
    fi

    log_info "Installing Docker..."
    apt-get update
    apt-get install -y ca-certificates curl gnupg lsb-release

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    # Add current user to docker group
    if [ -n "${SUDO_USER:-}" ]; then
        usermod -aG docker "$SUDO_USER"
        log_info "Added $SUDO_USER to docker group. Log out and back in for changes to take effect."
    fi
}

install_docker

# Ensure docker compose plugin works
if ! docker compose version &> /dev/null; then
    log_error "Docker Compose plugin not available. Please install it manually."
    exit 1
fi

# ============================================================
# 2. Create application directory
# ============================================================
log_info "Creating application directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR/data/db"
mkdir -p "$INSTALL_DIR/data/cache"
mkdir -p "$INSTALL_DIR/data/caddy-data"
mkdir -p "$INSTALL_DIR/data/caddy-config"

# ============================================================
# 3. Check for .env file
# ============================================================
if [ ! -f "$INSTALL_DIR/.env" ]; then
    log_warn ".env file not found at $INSTALL_DIR/.env"
    log_warn "Please copy the .env file generated by infra/deploy.sh"
    log_warn "Example:"
    log_warn "  scp .env.deploy azureuser@your-vm-ip:/opt/photosync/.env"
    log_warn ""
    log_warn "Creating placeholder .env..."
    cat > "$INSTALL_DIR/.env" <<'EOF'
# Placeholder - Replace with real values from .env.deploy
AZURE_STORAGE_ACCOUNT=youraccount
AZURE_STORAGE_KEY=yourkey
AZURE_STORAGE_CONTAINER=photos
AZURE_STORAGE_TIER=Cool
SECRET_KEY=change-me-to-random-string
PHOTOSYNC_PASSWORD=family
EOF
    chmod 600 "$INSTALL_DIR/.env"
fi

# ============================================================
# 4. Create docker-compose.yml
# ============================================================
log_info "Creating docker-compose.yml..."
cat > "$INSTALL_DIR/docker-compose.yml" <<'EOF'
version: "3.8"

services:
  backend:
    image: ghcr.io/photosync/photosync-backend:latest
    # Or build locally:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    container_name: photosync-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/db/photosync.db
      - THUMBNAIL_CACHE_DIR=/app/data/cache
    volumes:
      - ./data/db:/app/data/db
      - ./data/cache:/app/data/cache
    networks:
      - photosync-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  caddy:
    image: caddy:2-alpine
    container_name: photosync-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config
      - ./data/cache:/srv/thumbnails:ro
    networks:
      - photosync-net
    depends_on:
      - backend

networks:
  photosync-net:
    driver: bridge
EOF

# ============================================================
# 5. Create Caddyfile
# ============================================================
log_info "Creating Caddyfile..."
mkdir -p "$INSTALL_DIR/caddy"
cat > "$INSTALL_DIR/caddy/Caddyfile" <<'EOF'
# Replace photosync.yourdomain.com with your actual domain
# For local testing without domain, replace with ":80"

:80 {
    # API requests
    reverse_proxy /api/* backend:8000 {
        header_up Host {host}
        header_up X-Real-IP {remote}
        header_up X-Forwarded-For {remote}
        header_up X-Forwarded-Proto {scheme}
    }

    # Health check
    reverse_proxy /health backend:8000

    # Thumbnails direct from disk
    handle /thumbnails/* {
        root * /srv/thumbnails
        file_server
        header Cache-Control "public, max-age=2592000"
    }

    # Everything else to backend
    reverse_proxy backend:8000

    encode gzip zstd
}
EOF

# ============================================================
# 6. Build or pull image
# ============================================================
log_info "Building backend image..."
cd "$INSTALL_DIR"

# If we have local backend code, build it. Otherwise we'll pull from registry.
if [ -d "$INSTALL_DIR/backend" ] && [ -f "$INSTALL_DIR/backend/Dockerfile" ]; then
    docker compose build --no-cache
else
    log_warn "No local backend/ directory found."
    log_warn "You need to either:"
    log_warn "  1. Copy backend/ code to $INSTALL_DIR/backend and run again, OR"
    log_warn "  2. Update docker-compose.yml to use a pre-built image"
    log_warn ""
    log_warn "For now, creating a placeholder..."
    mkdir -p "$INSTALL_DIR/backend"
fi

# ============================================================
# 7. Start services
# ============================================================
log_info "Starting services..."
docker compose up -d

# ============================================================
# 8. Wait for health check
# ============================================================
log_info "Waiting for backend to be healthy..."
for i in {1..30}; do
    if curl -sf http://localhost:8000/health &> /dev/null; then
        log_info "Backend is healthy!"
        break
    fi
    echo -n "."
    sleep 2
done

# ============================================================
# 9. Create systemd service for auto-start
# ============================================================
log_info "Creating systemd service for auto-start..."
cat > /etc/systemd/system/photosync.service <<EOF
[Unit]
Description=PhotoSync Docker Compose
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$INSTALL_DIR
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable photosync.service

# ============================================================
# 10. Setup daily backup cron job
# ============================================================
log_info "Setting up daily database backup..."
cat > "$INSTALL_DIR/scripts/backup-db.sh" <<'BACKUP_EOF'
#!/usr/bin/env bash
set -euo pipefail
INSTALL_DIR="/opt/photosync"
DB_FILE="$INSTALL_DIR/data/db/photosync.db"
BACKUP_NAME="photosync-$(date +%Y%m%d_%H%M%S).db"

if [ ! -f "$DB_FILE" ]; then
    echo "Database not found, skipping backup"
    exit 0
fi

# Load env
export $(grep -v '^#' "$INSTALL_DIR/.env" | xargs)

az storage blob upload \
    --account-name "$AZURE_STORAGE_ACCOUNT" \
    --account-key "$AZURE_STORAGE_KEY" \
    --container-name backups \
    --name "$BACKUP_NAME" \
    --file "$DB_FILE" \
    --tier Archive \
    --output none

echo "Backup completed: $BACKUP_NAME"
BACKUP_EOF

mkdir -p "$INSTALL_DIR/scripts"
chmod +x "$INSTALL_DIR/scripts/backup-db.sh"

# Add cron job
echo "0 3 * * * root $INSTALL_DIR/scripts/backup-db.sh >> /var/log/photosync-backup.log 2>&1" > /etc/cron.d/photosync-backup

# ============================================================
# 11. Summary
# ============================================================
PUBLIC_IP=$(curl -s -H Metadata:true --noproxy '*' \
    'http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0/publicIpAddress?api-version=2021-02-01&format=text' || echo "unknown")

echo ""
echo "============================================================"
echo -e "${GREEN}PhotoSync VM Setup Complete!${NC}"
echo "============================================================"
echo ""
echo "Install Directory:  $INSTALL_DIR"
echo "Public IP:          $PUBLIC_IP"
echo ""
echo "Services:"
echo "  docker compose ps"
echo ""
echo "Logs:"
echo "  docker compose logs -f backend"
echo "  docker compose logs -f caddy"
echo ""
echo "Health Check:"
echo "  curl http://localhost:8000/health"
echo ""
echo "Backup:"
echo "  Daily at 3:00 AM to Blob Archive tier"
echo "  Manual: $INSTALL_DIR/scripts/backup-db.sh"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Update Caddyfile with your domain (edit $INSTALL_DIR/caddy/Caddyfile)"
echo "  2. Open NSG ports 80 and 443 in Azure Portal"
echo "  3. Optionally setup Cloudflare for CDN"
echo ""
